

# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`


In [26]:
import numpy as np
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

In [44]:
b=np.zeros(10)
b[4]=1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`


In [28]:
c=np.arange(10,49)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [32]:
d=np.arange(0,9).reshape((3, 3))
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [63]:
p=np.array([1,2,0,0,4,0])
p[np.nonzero(p)]


array([1, 2, 4])

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [64]:
f=np.eye(3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [65]:
random_a = np.random.random((3,3,3))
random_a

array([[[0.64304094, 0.79886091, 0.64625987],
        [0.34663998, 0.66664362, 0.63660852],
        [0.37292407, 0.48780201, 0.11545666]],

       [[0.11059459, 0.78046628, 0.82336859],
        [0.86539768, 0.2089114 , 0.64991726],
        [0.08024683, 0.50377994, 0.77807258]],

       [[0.17233716, 0.43596311, 0.16968228],
        [0.71028704, 0.61875857, 0.02841153],
        [0.65404353, 0.12101106, 0.87890353]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [66]:
b_random=np.random.random((10,10))
print("min numberis : ", np.min(b_random),"and max number is:", np.max(b_random))

min numberis :  0.020200920088049856 and max number is: 0.9818657863387142


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [67]:
c_random=np.random.random((30))
c_mean=np.mean(c_random)
print(c_mean)

0.5241294177757378


#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [70]:
a_dg=np.diag([1,2,3,4,5])
a_dg

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [76]:
d_random=np.random.random((5,5))
x = (d_random - np.mean(d_random))/np.std(d_random)
x

array([[ 0.74941817, -0.26264825,  0.3403097 ,  0.72915876, -1.61304942],
       [ 1.27911877, -1.53418645,  1.04314192, -1.09414415,  1.31052883],
       [-0.78708827,  0.84511033,  0.3148817 , -0.07576778,  1.28870414],
       [-1.7233571 , -1.60347382, -0.61853169, -0.72326287, -1.00614137],
       [ 0.90770097,  0.45829667,  0.97727305,  0.76054616,  0.037462  ]])

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [94]:
h_random=np.random.random((10))
print(np.sort(h_random))

[0.03463251 0.045606   0.15316849 0.16986899 0.20146652 0.27889496
 0.32331849 0.64849043 0.83585174 0.88985126]


#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [97]:
k_random=np.random.random((10))
k_random[k_random.argmax()]=0
k_random

array([0.44563866, 0.19740831, 0.59973064, 0.31733573, 0.05971365,
       0.84221115, 0.64944203, 0.27311537, 0.        , 0.79887789])

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [111]:
k = np.random.randint(0, 10, (3, 3))
print(k)
s = k - k.mean(axis=1, keepdims=True)
print(s)

[[8 2 1]
 [9 8 4]
 [0 1 5]]
[[ 4.33333333 -1.66666667 -2.66666667]
 [ 2.          1.         -3.        ]
 [-2.         -1.          3.        ]]


#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

In [130]:
z= np.arange(10000)
np.random.shuffle(Z)
n = 5
z_sort=np.argsort(z)
z_part=z[np.argpartition(z, 5)]
print(z_sort)
print(z_part)



[   0    1    2 ... 9997 9998 9999]
[   1    0    2 ... 9997 9998 9999]



#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`

In [137]:
gr=np.random.randint(0, 10, (5, 3))
gh=np.where(gr < 5, gr, j**2)


array([[9, 2, 6],
       [6, 2, 0],
       [5, 9, 3],
       [2, 3, 1],
       [2, 2, 9]])